export const zones = [
  {
    id: 'kwamhlanga',
    name: 'Kwamhlanga',
    eta: '18-28 min',
    coverage: 'A, B, D and the school corridors',
    blurb: 'Quick evening runs built around homes, clinics, and busy learner pickup points.',
  },
  {
    id: 'kwaggafontein',
    name: 'Kwaggafontein',
    eta: '24-34 min',
    coverage: 'Main road, extensions, and taxi-rank pickups',
    blurb: 'Wider routing with landmark-based drop-offs to keep riders moving without confusion.',
  },
]

export const stats = [
  {
    id: 'riders',
    label: 'Active riders',
    value: '32',
    detail: 'Shared across dinner rush and school-route pickups.',
  },
  {
    id: 'avg-time',
    label: 'Average arrival',
    value: '23 min',
    detail: 'Based on tonight’s route bundle for the selected service area.',
  },
  {
    id: 'rating',
    label: 'Neighbour rating',
    value: '4.8 / 5',
    detail: 'People rate clearer drop points and simpler cash handoffs.',
  },
]

export const vendors = [
  {
    id: 'spaza-flame-grill',
    name: 'Spaza Flame Grill',
    area: 'Kwamhlanga A',
    tagline: 'Late grill plates, loaded chips, and kota favourites.',
    description:
      'A strong evening seller for grilled chicken, spiced wings, and quick kota builds near the taxi flow.',
    rating: 4.9,
    eta: '18-26 min',
    deliveryFee: 18,
    heroLabel: 'SFG',
    spotlight: 'linear-gradient(135deg, #f97316 0%, #ea580c 45%, #7c2d12 100%)',
    zoneIds: ['kwamhlanga', 'kwaggafontein'],
    categories: ['Shisanyama', 'Kota', 'Street grill'],
    menu: [
      {
        id: 'half-chicken-pap',
        name: 'Half Chicken and Pap',
        description: 'Fire-grilled half chicken with chakalaka and soft pap.',
        price: 95,
        prepMinutes: 20,
        badge: 'Top seller',
      },
      {
        id: 'kota-firecracker',
        name: 'Firecracker Kota',
        description: 'Polony, chips, egg, achar, Russian, and house chilli sauce.',
        price: 68,
        prepMinutes: 14,
        badge: 'Street favourite',
      },
      {
        id: 'wings-loaded-fries',
        name: 'Wings and Loaded Fries',
        description: 'Sticky wings on masala fries with creamy slaw.',
        price: 82,
        prepMinutes: 16,
      },
      {
        id: 'family-grill-pack',
        name: 'Family Grill Pack',
        description: 'Quarter chicken pieces, wors, pap, and two liter cola.',
        price: 210,
        prepMinutes: 28,
        badge: 'Weekend combo',
      },
    ],
  },
  {
    id: 'mam-lindiwe-kitchen',
    name: 'Mam Lindiwe Kitchen',
    area: 'Kwaggafontein Extension 6',
    tagline: 'Home-style plates for lunchboxes and supper tables.',
    description:
      'Known for rich stews, warm samp, and portions that travel well to homes and local pickup points.',
    rating: 4.8,
    eta: '22-32 min',
    deliveryFee: 20,
    heroLabel: 'MLK',
    spotlight: 'linear-gradient(135deg, #f59e0b 0%, #b45309 52%, #78350f 100%)',
    zoneIds: ['kwaggafontein', 'kwamhlanga'],
    categories: ['Home plates', 'Stew bowls', 'Lunch specials'],
    menu: [
      {
        id: 'beef-stew-plate',
        name: 'Beef Stew Plate',
        description: 'Tender beef stew with rice, pumpkin, and spinach.',
        price: 89,
        prepMinutes: 18,
        badge: 'Comfort meal',
      },
      {
        id: 'samp-beans-bowl',
        name: 'Samp and Beans Bowl',
        description: 'Creamy samp mix with grilled chicken strips and gravy.',
        price: 74,
        prepMinutes: 17,
      },
      {
        id: 'mogodu-saturday',
        name: 'Saturday Mogodu',
        description: 'Slow-cooked tripe with pap and a tomato onion relish.',
        price: 84,
        prepMinutes: 24,
        badge: 'Weekend special',
      },
      {
        id: 'lunchbox-combo',
        name: 'Lunchbox Combo',
        description: 'Pap, chicken stew, beetroot, and cabbage for school or work.',
        price: 69,
        prepMinutes: 15,
      },
    ],
  },
  {
    id: 'majita-burger-stop',
    name: 'Majita Burger Stop',
    area: 'Kwamhlanga D',
    tagline: 'Burgers, slap chips, and fast night snacks.',
    description:
      'A youth-driven menu with crispy burgers, loaded wraps, and fries built for sports-field hunger.',
    rating: 4.7,
    eta: '16-24 min',
    deliveryFee: 16,
    heroLabel: 'MBS',
    spotlight: 'linear-gradient(135deg, #14b8a6 0%, #0f766e 48%, #134e4a 100%)',
    zoneIds: ['kwamhlanga'],
    categories: ['Burgers', 'Wraps', 'Snack boxes'],
    menu: [
      {
        id: 'double-cheese-burger',
        name: 'Double Cheese Burger',
        description: 'Two beef patties, melty cheese, slap chips, and smoked mayo.',
        price: 78,
        prepMinutes: 12,
        badge: 'Fast mover',
      },
      {
        id: 'crispy-chicken-wrap',
        name: 'Crispy Chicken Wrap',
        description: 'Crispy fillet, crunchy salad, and peri-peri drizzle.',
        price: 72,
        prepMinutes: 11,
      },
      {
        id: 'street-box',
        name: 'Street Snack Box',
        description: 'Mini burger, wings, fries, and a cold drink.',
        price: 99,
        prepMinutes: 15,
        badge: 'All-in-one',
      },
      {
        id: 'masala-fries',
        name: 'Masala Fries Tub',
        description: 'Crisp chips tossed with masala spice and garlic sauce.',
        price: 38,
        prepMinutes: 8,
      },
    ],
  },
  {
    id: 'nala-pizza-kota',
    name: 'Nala Pizza and Kota',
    area: 'Kwaggafontein Main Road',
    tagline: 'Shareable pizza trays with township topping energy.',
    description:
      'Pizza for family nights, plus kota-inspired slices and wings for group orders around the main road.',
    rating: 4.6,
    eta: '25-34 min',
    deliveryFee: 22,
    heroLabel: 'NPK',
    spotlight: 'linear-gradient(135deg, #fb7185 0%, #be123c 52%, #881337 100%)',
    zoneIds: ['kwaggafontein'],
    categories: ['Pizza', 'Wings', 'Group orders'],
    menu: [
      {
        id: 'street-meat-pizza',
        name: 'Street Meat Pizza',
        description: 'Steak, Russian slices, peppers, and mozzarella on a large base.',
        price: 126,
        prepMinutes: 22,
        badge: 'Party pick',
      },
      {
        id: 'chicken-mayo-pizza',
        name: 'Chicken Mayo Pizza',
        description: 'Creamy chicken mayo base with sweet peppers and herbs.',
        price: 118,
        prepMinutes: 21,
      },
      {
        id: 'wings-share-basket',
        name: 'Wings Share Basket',
        description: 'Twelve saucy wings with wedges and two dips.',
        price: 112,
        prepMinutes: 18,
      },
      {
        id: 'pizza-kota-pocket',
        name: 'Pizza Kota Pocket',
        description: 'Folded pizza pocket packed with chips, cheese, and beef strips.',
        price: 64,
        prepMinutes: 13,
        badge: 'Local twist',
      },
    ],
  },
]
